[package]
name = "build_scripts"
version = "0.1.0"
authors = ["dreamflytly <dreamflytly@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0"
pkg-config="0.3.16"
